name: di4l_pos
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.0.1
  get: ^4.6.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0

  # DI
  get_it: ^7.2.0
  injectable: ^2.1.0

  # Support UI
  flutter_local_notifications: ^9.5.3+1
  after_layout: ^1.2.0
  bmprogresshud: ^1.0.0
  cached_network_image: ^3.2.0
  nb_utils: ^4.5.2
  auto_size_text: ^3.0.0
  marquee: ^2.2.3
  webview_flutter: ^3.0.1
  we_slide: ^2.3.0
  responsive_builder: ^0.4.2
  expandable: ^5.0.1
  syncfusion_flutter_datagrid: ^20.1.61
  anim_search_bar: ^2.0.3
  badges: ^3.0.2
  lottie: ^1.4.2
  flutter_lints: ^2.0.1
  fl_chart: ^0.61.0
  intl: ^0.18.0

  # Networks
  retrofit: ^3.3.1
  dio: ^4.0.6
  logger: ^1.1.0

  # Firebase
  firebase_core: ^2.8.0
  firebase_messaging: ^14.2.6
  firebase_messaging_web: ^3.2.17
  firebase_crashlytics: ^3.3.3

  # Storage
  shared_preferences: ^2.0.7

  # Barcode
  mobile_scanner: ^2.0.0
  barcode: ^2.2.1
  barcode_widget: ^2.0.2

  # Socials Login
  google_sign_in: ^5.0.7
  sign_in_with_apple: ^4.0.0

  # Utils
  tiengviet: ^0.5.0

  # Web
  url_strategy: ^0.2.0

  #flutter_scrolling_fab_animated
  flutter_scrolling_fab_animated: ^0.1.4

  radio_grouped_buttons: ^1.0.1

  #flutter_masked_text2: ^0.9.1
  flutter_masked_text2: ^0.9.1

  cupertino_icons: ^1.0.0
  image_picker: ^0.8.5+3
  http_parser: ^4.0.2
  buttons_tabbar: ^1.3.6
  flutter_calendar_carousel: ^2.4.1
  font_awesome_flutter: ^10.4.0
  flutter_staggered_grid_view: ^0.6.2
  equatable: ^2.0.5
  flutter_slidable: ^2.0.0
  google_maps_flutter: ^2.2.5
  dvhcvn: ^2.0.20221001
  scrollable_table_view: ^1.0.1
  bottom_sheet_expandable_bar: ^0.1.2
  flutter_speed_dial: ^6.2.0
  fab_circular_menu: ^1.0.2
  readmore: ^2.2.0
  syncfusion_flutter_charts: ^20.4.54
  awesome_dialog: ^3.0.2
  url_launcher: ^6.1.10
  calendar_date_picker2: ^0.5.2
  search_page: ^2.3.0
  getwidget: ^3.1.1

  toggle_switch: ^2.1.0
  theme_provider: ^0.6.0
  flutter_math_fork: ^0.6.3+1
  quantity_input: ^1.0.2
  cupertino_date_textbox: ^1.0.3
  input_quantity: ^1.2.1
  expandable_widgets: ^1.0.3+1
  webview_flutter_plus: ^0.3.0+2
  flutter_html: ^3.0.0-beta.2
  carousel_slider: ^4.2.1

dependency_overrides:
  url_launcher_web: 2.0.6
  flutter_svg: 0.22.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.0
  build_runner: ^2.3.3
  retrofit_generator: ^4.2.0
  flutter_launcher_icons: ^0.9.1
  analyzer: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/pos_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/home/
    - assets/svg/
    - assets/locales/
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 600
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 600
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Bold.ttf
          weight: 600
